### PR TITLE
Add ADC driver

### PR DESCRIPTION
**Pull request by Tuetuopay**
This PR adds an ADC driver directly ported from the stm32f1xx-hal crate.

Basic functionality has been tested on the Longan Nano board.

### CODE REVIEW

**Comment by Tuetuopay** [comment]
Aaaand there's already a PR for this driver 🤦

**Comment by dkhayes117** [comment]
@Tuetuopay   I'm testing the DMA functionality for your PR before I merge it, and I'm having trouble with it.  Was you able to test the DMA portion? Could you share your test code if so?  I am unable to build a DMA example without using adding the `singleton!` macro like used in cortex-m.  Thanks!

**Comment by dkhayes117** [comment]
Everything looks good on this PR, I got DMA working with a static mut buffer without the singleton! macro.

**Comment by Tuetuopay** [comment]
I am so sorry for not responding to your question, I had some personal stuff on my mind and had no time to touch a GD32Fv103 since opening this PR.

So glad you got  working! In theory, code that works on a legit STM32F103 should « just work (TM) » since this is a very straightforward port. Would you mind adding the test code, so that it serves as a basic « hello world » for DMA?

I don’t know how I feel about the static mut buffer. Semantically, it does totally makes sense when dealing with DMA (a DMA peripheral is ‘static, isn’t it?), though I don’t have enough experience with competing chips to tell whether there is a better way…

**Comment by dkhayes117** [comment]
The adc dma methods require `stable_deref_trait::StableDeref` and `DerefMut` traits which I got by using a static mut buffer.  I'm sure there are other ways to do this, but I just needed something to test that the dma worked.  Users can use whatever method works for them.  I am merging this now I've tested it :)

**Pull request merged**
